const locationData = {
  place_id: 0,
  licence: 'string',
  osm_type: 'string',
  osm_id: 0,
  boundingbox: [''],
  lat: 0,
  lon: 0,
  display_name: 'string',
  class: 'string',
  type: 'string',
  importance: 0,
  icon: 'string',
}

export const ModiteProfile = {
  title: '',
  phone: '',
  skype: '',
  real_name: '',
  real_name_normalized: '',
  display_name: '',
  display_name_normalized: '',
  fields: {
    'Skype User': '',
    'Name Pronunciation': '',
    'Start Date': '',
    Location: '',
    'Current Project': '',
    Position: '',
    Bio: '',
    Bday: '',
    'Preferred Pronoun': '',
    locationData: locationData,
    'GitHub User': '',
  },
  status_text: '',
  status_emoji: '',
  status_expiration: 0,
  avatar_hash: '',
  image_original: '',
  is_custom_image: false,
  email: '',
  first_name: '',
  last_name: '',
  image_24: '',
  image_32: '',
  image_48: '',
  image_72: '',
  image_192: '',
  image_512: '',
  image_1024: '',
  status_text_canonical: '',
}
